import React, { useMemo, useState } from 'react';

export default function Explanation({ explanation, loading, riskScore }) {
  const [showReasoning, setShowReasoning] = useState(false);

  const parsedData = useMemo(() => {
    if (!explanation || !explanation.explanation) return null;
    try {
      return JSON.parse(explanation.explanation);
    } catch (e) {
      return {
        headline: "Clinical Synthesis",
        personalized_summary: explanation.explanation,
        score_breakdown: null,
        risk_vectors: null,
        behaviour_change_tips: null,
        ai_meta: null
      };
    }
  }, [explanation]);

  if (loading) {
    return (
      <section className="bg-surface-container-lowest border border-outline-variant rounded-xl p-lg shadow-sm h-full flex flex-col relative overflow-hidden">
        <div className="absolute top-0 left-0 w-full h-1 bg-primary animate-pulse"></div>
        <h2 className="text-headline-sm font-headline-sm text-primary border-b border-outline-variant pb-sm mb-md flex items-center gap-xs animate-pulse">
          <span className="material-symbols-outlined text-secondary">neurology</span>
          Generating Clinical Synthesis...
        </h2>
        <div className="space-y-md animate-pulse">
          <div className="h-4 bg-surface-container-high rounded w-full"></div>
          <div className="h-4 bg-surface-container-high rounded w-5/6"></div>
          <div className="h-4 bg-surface-container-high rounded w-4/6"></div>
        </div>
      </section>
    );
  }

  if (!parsedData) return null;

  const totalPoints = parsedData.score_breakdown?.components?.reduce((sum, comp) => sum + comp.points, 0) || 1;
  const colors = ['bg-error', 'bg-warning', 'bg-primary', 'bg-secondary', 'bg-tertiary'];
  
  const aiMeta = parsedData.ai_meta;
  const confidence = aiMeta?.confidence || 0.88;
  const generatedBy = aiMeta?.generated_by || "Rule engine + clinical knowledge base";

  return (
    <section className="bg-surface-container-lowest border border-outline-variant rounded-xl p-lg shadow-sm h-full flex flex-col relative overflow-hidden animate-fade-in print:shadow-none print:border-none print:p-0 print:mt-md">
      <div className="flex items-center justify-between border-b border-outline-variant pb-sm mb-md">
        <h2 className="text-headline-sm font-headline-sm text-primary flex items-center gap-xs">
          <span className="material-symbols-outlined text-secondary" style={{fontVariationSettings: "'FILL' 1"}}>neurology</span>
          Generated Clinical Summary <span className="text-body-sm font-normal text-on-surface-variant ml-2">(AI-assisted, rule-based)</span>
        </h2>
        <div className="flex gap-2 items-center">
          <span className="font-label-sm text-label-sm text-on-surface-variant bg-surface-container-high px-2 py-1 rounded border border-outline-variant uppercase tracking-widest text-[10px]" title={`Generated by: ${generatedBy}`}>
            Confidence: {confidence.toFixed(2)}
          </span>
          <span className="font-label-sm text-label-sm text-on-surface-variant bg-surface-container-high px-2 py-1 rounded border border-outline-variant uppercase tracking-widest text-[10px]">
            {explanation.filtered ? "RULE ENGINE" : "LLM + RULES"}
          </span>
        </div>
      </div>
      
      <div className="mb-md">
        <h3 className="text-headline-sm font-headline-sm text-primary mb-2">{parsedData.headline}</h3>
        <p className="text-body-md font-body-md text-on-surface-variant">{parsedData.personalized_summary}</p>
      </div>

      {/* Behaviour Change Tips */}
      {parsedData.behaviour_change_tips && parsedData.behaviour_change_tips.length > 0 && (
        <div className="mb-lg bg-tertiary-container/30 border border-outline-variant rounded-lg p-md">
          <h4 className="text-label-md font-bold text-on-surface mb-3 flex items-center gap-2">
            <span className="material-symbols-outlined text-primary text-lg">tips_and_updates</span>
            What You Can Do Differently
          </h4>
          <ul className="space-y-3">
            {parsedData.behaviour_change_tips.map((tip, i) => (
              <li key={i} className="text-body-sm text-on-surface-variant flex items-start gap-3">
                <span className="material-symbols-outlined text-primary text-sm mt-0.5 shrink-0" style={{fontVariationSettings: "'FILL' 1"}}>check_circle</span>
                <span>{tip}</span>
              </li>
            ))}
          </ul>
        </div>
      )}

      {parsedData.score_breakdown && parsedData.score_breakdown.components && parsedData.score_breakdown.components.length > 0 && (
        <div className="mb-xl bg-surface-container-lowest border border-outline-variant rounded-lg p-md">
          <div className="flex justify-between items-end mb-2">
            <h4 className="text-label-md font-bold text-on-surface flex items-center gap-1 group relative cursor-help">
              Score Breakdown
              <span className="material-symbols-outlined text-sm text-outline">help</span>
              <div className="absolute bottom-full left-0 mb-2 hidden group-hover:block w-64 bg-surface-container-highest text-on-surface text-xs p-2 rounded shadow-lg z-10 font-normal">
                Points are added for each risky behavior identified. Higher score = greater misuse risk. 0-30 = Low, 31-60 = Medium, 61+ = High.
              </div>
            </h4>
            <span className="text-headline-md font-bold text-primary">{riskScore ? `${(riskScore * 10).toFixed(0)}` : '—'}/100</span>
          </div>
          
          {/* Horizontal Stacked Bar */}
          <div className="w-full h-4 rounded-full flex overflow-hidden mb-4 bg-surface-container-highest">
            {parsedData.score_breakdown.components.map((comp, i) => (
              <div 
                key={i} 
                className={`h-full ${colors[i % colors.length]}`} 
                style={{ width: `${(comp.points / totalPoints) * 100}%` }}
                title={`${comp.label}: +${comp.points}`}
              ></div>
            ))}
          </div>

          <div className="space-y-2 mt-4">
            {parsedData.score_breakdown.components.map((comp, i) => (
              <div key={i} className="flex justify-between items-center bg-surface-container-lowest text-sm">
                <div className="flex items-center gap-2">
                  <span className={`w-3 h-3 rounded-full ${colors[i % colors.length]}`}></span>
                  <span className="font-medium text-on-surface">{comp.label}</span>
                </div>
                <div className="flex gap-4">
                  <span className="text-on-surface-variant hidden md:block text-xs">{comp.reason}</span>
                  <span className="text-primary font-bold">+{comp.points}</span>
                </div>
              </div>
            ))}
          </div>
        </div>
      )}

      {/* Risk Trajectory Chart Removed from here */}

      {/* Reasoning Steps Accordion — now uses dynamic ai_meta data */}
      <div className="mb-lg border border-outline-variant rounded-lg overflow-hidden mt-6">
        <button 
          onClick={() => setShowReasoning(!showReasoning)}
          className="w-full flex justify-between items-center p-md bg-surface hover:bg-surface-container-low transition-colors text-left"
        >
          <span className="font-label-md font-bold text-on-surface flex items-center gap-2">
            <span className="material-symbols-outlined text-secondary text-sm">account_tree</span>
            View Reasoning Steps & Sources
          </span>
          <span className="material-symbols-outlined text-on-surface-variant transition-transform" style={{transform: showReasoning ? 'rotate(180deg)' : 'rotate(0deg)'}}>
            expand_more
          </span>
        </button>
        {showReasoning && (
          <div className="p-md bg-surface-container-lowest border-t border-outline-variant flex flex-col gap-md">
            {/* Dynamic Reasoning Steps */}
            <div className="flex flex-col gap-sm">
              <h5 className="text-label-sm font-bold text-on-surface uppercase tracking-wider">Analysis Steps</h5>
              {(aiMeta?.reasoning_steps || [
                "Matched behaviors to clinical misuse patterns.",
                "Cross-referenced with WHO/ICMR/CDC guidelines.",
                "Computed composite risk score and assigned band."
              ]).map((step, i) => (
                <div key={i} className="flex items-start gap-3">
                  <div className="w-6 h-6 rounded-full bg-primary/10 text-primary flex items-center justify-center font-bold text-xs shrink-0 mt-0.5">{i + 1}</div>
                  <p className="text-body-sm text-on-surface-variant">{step}</p>
                </div>
              ))}
            </div>

            {/* Evidence Sources */}
            <div className="border-t border-outline-variant pt-md">
              <h5 className="text-label-sm font-bold text-on-surface uppercase tracking-wider mb-2">Evidence Sources</h5>
              <div className="flex flex-wrap gap-2">
                {(aiMeta?.evidence_sources || [
                  "WHO AWaRe Guidelines",
                  "ICMR AMR Action Plan",
                  "CDC 'Be Antibiotics Aware'"
                ]).map((source, i) => (
                  <span key={i} className="text-[10px] bg-secondary-container text-on-secondary-container px-2 py-1 rounded font-medium">
                    {source}
                  </span>
                ))}
              </div>
            </div>

            {/* Safety Disclaimer */}
            {aiMeta?.safety_disclaimer && (
              <div className="border-t border-outline-variant pt-md">
                <div className="flex items-start gap-2 bg-error-container/30 p-sm rounded">
                  <span className="material-symbols-outlined text-error text-sm mt-0.5">gpp_maybe</span>
                  <p className="text-body-sm text-on-surface-variant italic">{aiMeta.safety_disclaimer}</p>
                </div>
              </div>
            )}
          </div>
        )}
      </div>

      {/* CTAs */}
      <div className="mt-xl pt-lg border-t border-outline-variant flex flex-wrap gap-md justify-end print:hidden">
        <button onClick={() => window.location.href = '/learn'} className="px-4 py-2 text-primary hover:bg-primary/10 rounded transition-colors text-label-md font-bold">
          Learn More
        </button>
        <button onClick={() => window.print()} className="px-4 py-2 border border-primary text-primary hover:bg-primary/10 rounded transition-colors text-label-md font-bold flex items-center gap-2">
          <span className="material-symbols-outlined text-sm">download</span>
          Save PDF
        </button>
        <button onClick={() => window.location.href = '/'} className="px-4 py-2 bg-primary text-on-primary hover:bg-primary/90 rounded transition-colors text-label-md font-bold">
          Retake Assessment
        </button>
      </div>
    </section>
  );
}
